/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package NguyenLieu;

import MySQLDB.NguyenlieuDAO;
import static MySQLDB.NguyenlieuDAO.GetId;
import MySQLDB.NhapkhoDAO;
import MySQLDB.Shared;
import TrangChu.TrangChu;
import java.util.ArrayList;
import java.util.Stack;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.Nguyenlieu;
import pojo.NhapKhoModel;

/**
 *
 * @author nguye
 */
public class NguyenLieu_GUI extends javax.swing.JFrame {

    /**
     * Creates new form NguyenLieu_GUI
     */
    DefaultTableModel dtm = new DefaultTableModel();
    private Object Int;
    DefaultTableModel dtm2 = new DefaultTableModel();
    private ArrayList<NhapKhoModel> danhSach = null;

    public NguyenLieu_GUI() {
        String Tieude[] = {"Mã Nguyên Liệu", "Tên Nguyên Liệu", "Số Lượng Tồn"};
        dtm.setColumnIdentifiers(Tieude);
        initComponents();
        load_tableMon(new NguyenlieuDAO().laydulieunguyenlieu());
        setLocationRelativeTo(null);
        jTextField3.setEnabled(false);

        //nhap kho
//        String TieudeNhapKho[] = {"Mã Nhập Kho", "Tên Nguyên Liệu Nhập","Số Lượng"};
//        dtm2.setColumnIdentifiers(TieudeNhapKho);
//        NhapkhoDAO nhapkhodao = new NhapkhoDAO();
//        load_tableKho(new NhapkhoDAO().laydulieuNhapKho());
    }

    private void load_tableMon(ArrayList<Nguyenlieu> danhSach) {
        dtm.setRowCount(0);
        for (Nguyenlieu pb : danhSach) {
            Vector<Object> v = new Stack<>();
            v.add(pb.getMaNguyenLieu());
            v.add(pb.getTenNguyenLieu());
            v.add(pb.getSoluongton());
            dtm.addRow(v);
        }
        jTable2.setModel(dtm);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Nguyên Liệu");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Nguyên liệu"));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Xóa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Sửa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel3.setText("Tên Nguyên Liệu:");

        jLabel4.setText("Số Lượng :");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Mã Nguyên Liệu :");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton5.setText("Tìm Kiếm");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Trang Chủ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addGap(30, 30, 30)
                        .addComponent(jButton6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(540, 540, 540))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String soluongton = jTextField1.getText();
        String tennguyenlieu = jTextField2.getText();

        Nguyenlieu mm = new Nguyenlieu();

        int Soluongton = Integer.parseInt(soluongton);
        mm.setSoluongton(Soluongton);
        mm.setTenNguyenLieu(tennguyenlieu);

        if (NguyenlieuDAO.insertNguyenlieu(mm)) {
            JOptionPane.showMessageDialog(this, "Thêm Thành Công", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
            load_tableMon(new NguyenlieuDAO().laydulieunguyenlieu());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int row = jTable2.getSelectedRow();
        int column = jTable2.getSelectedColumn();

        if (row != -1) { // Kiểm tra xem có dòng nào được chọn hay không
            String value = jTable2.getValueAt(row, 1).toString();
            String value2 = jTable2.getValueAt(row, 2).toString();
            String value3 = jTable2.getValueAt(row, 0).toString();
            // Hiển thị thông tin lên Textfield
            jTextField2.setText(value);
            jTextField1.setText(value2);
            jTextField3.setText(value3);
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int rowIndex = jTable2.getSelectedRow();
        if (rowIndex != -1) {
            Object idm = jTable2.getValueAt(rowIndex, 0); // Lấy giá trị ID từ cột đầu tiên của dòng được chọn
            if (idm != null) { // Kiểm tra xem ID có tồn tại không
                int id = Integer.parseInt(idm.toString()); // Chuyển đổi ID thành kiểu int
                boolean result = NguyenlieuDAO.xoanguyenlieu(id); // Gọi phương thức xóa món ăn với ID vừa lấy được
                if (result) {
                    JOptionPane.showMessageDialog(null, "Xóa thành công!");
                    load_tableMon(new NguyenlieuDAO().laydulieunguyenlieu());
                } else {
                    JOptionPane.showMessageDialog(null, "Xóa thất bại!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Không có ID để xóa!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn một dòng để xóa!");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        String tenNguyenLieu = jTextField2.getText();
        String maNguyenLieuStr = jTextField3.getText(); // Giả sử bạn có một jTextField để nhập mã nguyên liệu
        String soLuongTonStr = jTextField1.getText();

        // Validate that the ingredient name, ID, and quantity are not empty
        if (tenNguyenLieu != null && !tenNguyenLieu.isEmpty()
                && maNguyenLieuStr != null && !maNguyenLieuStr.isEmpty()
                && soLuongTonStr != null && !soLuongTonStr.isEmpty()) {

            try {
                // Convert the ID to an integer
                int maNguyenLieu = Integer.parseInt(maNguyenLieuStr);
                // Convert the quantity to an integer
                int soLuongTon = Integer.parseInt(soLuongTonStr);

                // Call the method to update the ingredient information
                boolean result = NguyenlieuDAO.capNhatnguyenlieu(maNguyenLieu, tenNguyenLieu, soLuongTon);

                // Show a message indicating whether the update was successful
                if (result) {
                    JOptionPane.showMessageDialog(null, "Cập nhật thành công!");
                    load_tableMon(NguyenlieuDAO.laydulieunguyenlieu());
                } else {
                    JOptionPane.showMessageDialog(null, "Cập nhật thất bại!");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Mã nguyên liệu và số lượng tồn phải là số nguyên hợp lệ!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập tên, mã nguyên liệu và số lượng tồn để cập nhật!");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String maNguyenLieuText = jTextField3.getText().trim();
        String tenNguyenLieuText = jTextField2.getText().trim();

        Integer maNguyenLieu = null;
        if (!maNguyenLieuText.isEmpty()) {
            try {
                maNguyenLieu = Integer.parseInt(maNguyenLieuText);
            } catch (NumberFormatException e) {
                // Handle invalid integer input
                JOptionPane.showMessageDialog(this, "Mã nguyên liệu phải là số nguyên.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        String tenNguyenLieu = null;
        if (!tenNguyenLieuText.isEmpty()) {
            tenNguyenLieu = tenNguyenLieuText;
        }

        // Call the search method
        ArrayList<Nguyenlieu> resultList = NguyenlieuDAO.timkiemNguyenlieu(maNguyenLieu, tenNguyenLieu);

        // Display results in the table
        displayResults(resultList);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void displayResults(ArrayList<Nguyenlieu> resultList) {
        // Clear the existing rows in the table model
        dtm.setRowCount(0);

        // Populate the table model with the search results
        for (Nguyenlieu nl : resultList) {
            Vector<Object> row = new Vector<>();
            row.add(nl.getMaNguyenLieu());
            row.add(nl.getTenNguyenLieu());
            row.add(nl.getSoluongton());
            dtm.addRow(row);
        }

        // Update the table model
        jTable2.setModel(dtm);
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        NguyenLieu_GUI main = new NguyenLieu_GUI();

        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        dispose();
        TrangChu tc = new TrangChu();
        tc.setVisible(true);


    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed
//////////////////////////////////NHAP KHO ======================================

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NguyenLieu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NguyenLieu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NguyenLieu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NguyenLieu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NguyenLieu_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
