/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package NguyenLieu;

import MySQLDB.NguyenlieuDAO;
import static MySQLDB.NguyenlieuDAO.GetId;
import MySQLDB.NhapkhoDAO;
import static java.awt.SystemColor.menu;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Set;
import java.util.Stack;
import java.util.Vector;
import java.util.function.Supplier;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.DetailBillVer2;
import pojo.Nguyenlieu;
import pojo.NhapKhoModel;
import pojo.PhieuNhapKho_1;

/**
 *
 * @author nguye
 */
public class PhieuNhapKho extends javax.swing.JFrame {

//    DefaultTableModel dtm = new DefaultTableModel();
    private Object Int;
//    DefaultTableModel dtm2 = new DefaultTableModel();
//    private ArrayList<Nguyenlieu> danhSach = null;
//    private ArrayList<NhapKhoModel> danhSach1 = null;
    DefaultTableModel dtm = new DefaultTableModel();
    DefaultTableModel dtm2 = new DefaultTableModel();
    private ArrayList<Nguyenlieu> danhSach = null;
    private ArrayList<NhapKhoModel> danhSach1 = null;
    private ArrayList<PhieuNhapKho_1> list = new ArrayList();

    /**
     * Creates new form PhieuNhapKho
     */
    public PhieuNhapKho() {
//
//        initComponents();
//        String Tieude[] = {"Mã Nguyên Liệu", "Tên Nguyên Liệu", "Số Lượng Tồn"};
//        dtm.setColumnIdentifiers(Tieude);
//        load_tableMon(new NguyenlieuDAO().laydulieunguyenlieu());
//
//        String TieudeNhapKho[] = {"Mã Nguyên Liệu", "Tên Nguyên Liệu Nhập", "Số Lượng Nhập", "Ngày nhập"};
//        dtm2.setColumnIdentifiers(TieudeNhapKho);
//        NhapkhoDAO nhapkhodao = new NhapkhoDAO();
////
////        load_tableKho(new NhapkhoDAO().laydulieuNhapKho());
//
//        setLocationRelativeTo(null);
////        jTextField1.setEnabled(false);
//        setCurrentDate();
        initComponents();
        String Tieude[] = {"Mã Nguyên Liệu", "Tên Nguyên Liệu", "Số Lượng Tồn"};
        dtm.setColumnIdentifiers(Tieude);
        load_tableMon(new NguyenlieuDAO().laydulieunguyenlieu());

//        String TieudeNhapKho[] = {"Mã Nguyên Liệu", "Tên Nguyên Liệu Nhập", "Số Lượng Nhập", "Ngày nhập"};
//        dtm2.setColumnIdentifiers(TieudeNhapKho);
//        NhapkhoDAO nhapkhodao = new NhapkhoDAO();
        String[] tieuDeMoi = {"Mã Nguyên Liệu", "Tên Nguyên Liệu", "Số Lượng", "Ngày Nhập"};
        dtm2.setColumnIdentifiers(tieuDeMoi);
        load_tablePhieuNhapKho(list);
        setLocationRelativeTo(null);
        setCurrentDate();
//        jFormattedTextField1.setEnabled(false);
//        jTextField1.setEnabled(false);
//        jTextField2.setEnabled(false);
    }

    private void load_tableMon(ArrayList<Nguyenlieu> danhSach) {
        dtm.setRowCount(0);
        for (Nguyenlieu pb : danhSach) {
            Vector<Object> v = new Stack<>();
            v.add(pb.getMaNguyenLieu());
            v.add(pb.getTenNguyenLieu());
            v.add(pb.getSoluongton());
            dtm.addRow(v);
        }
        jTable1.setModel(dtm);
    }

    private void load_tablePhieuNhapKho(ArrayList<PhieuNhapKho_1> danhSach) {
        dtm2.setRowCount(0);
        for (PhieuNhapKho_1 pb : danhSach) {
            Vector<Object> v = new Stack<>();
            v.add(pb.getManguyenlieu());
            v.add(pb.getTennguyenlieu());
            v.add(pb.getSoluong());
            v.add(pb.getNgayNhap());
            dtm2.addRow(v);
        }
        jTable3.setModel(dtm2);
    }

//    private void load_tableKho(ArrayList<NhapKhoModel> danhSach) {
//        dtm2.setRowCount(0);
//        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
//        for (NhapKhoModel pb : danhSach) {
//            Vector<Object> v = new Stack<>();
//            v.add(pb.getMaNhapKho());
//            v.add(pb.getMaNguyenLieu());
//            v.add(pb.getSoLuongNhap());
//            v.add(pb.getNgayNhap());
//            dtm2.addRow(v);
//        }
//        jTable3.setModel(dtm2);
//    }
    private void setCurrentDate() {
        Date now = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String formattedDate = dateFormat.format(now);
        jFormattedTextField1.setText(formattedDate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSoLuongNhap = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Nhập Nguyên Liệu");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Mã Nguyên Liệu :");

        jLabel3.setText("Tên Nguyên Liệu :");

        jLabel4.setText("Số Lượng Nhập :");

        jButton1.setText("Thêm Nguyên Liệu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Xóa Nguyên Liêu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setText("Danh Sách Nhập Kho");

        jLabel6.setText("Ngày Nhập :");

        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });

        jButton5.setText("Nhập Nguyên Liệu");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(60, 60, 60)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(335, 335, 335))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField2)
                                    .addComponent(txtSoLuongNhap)
                                    .addComponent(jTextField1)
                                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtSoLuongNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        int column = jTable1.getSelectedColumn();

        if (row != -1) { // Kiểm tra xem có dòng nào được chọn hay không
            String value = jTable1.getValueAt(row, 0).toString();
            String value2 = jTable1.getValueAt(row, 1).toString();
            String value3 = jTable1.getValueAt(row, 2).toString();
            // Hiển thị thông tin lên Textfield
            jTextField1.setText(value);
            jTextField2.setText(value2);
//            jTextField2.setEditable(false);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
        Date now = new Date();

        // Định dạng ngày theo định dạng mong muốn
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");

        // Chuyển ngày hiện tại thành chuỗi theo định dạng đã chỉ định
        String formattedDate = dateFormat.format(now);

        // Đặt chuỗi ngày định dạng vào jFormattedTextField1
        jFormattedTextField1.setText(formattedDate);
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String manl = jTextField1.getText();
        int maNguyenlieu = Integer.parseInt(manl);
        String Tennl = jTextField2.getText();
        String SL = txtSoLuongNhap.getText();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date NgayNhap = null;
        try {
            NgayNhap = dateFormat.parse(jFormattedTextField1.getText());
        } catch (ParseException ex) {
            Logger.getLogger(PhieuNhapKho.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (SL.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền số lượng!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

//        PhieuNhapKho_1 pn = new PhieuNhapKho_1();
//        pn.setManguyenlieu(Integer.parseInt(manl));
//        pn.setSoluong(Integer.parseInt(SL));
//        pn.setTennguyenlieu(Tennl);
//        pn.setNgayNhap(NgayNhap);
//        list.add(pn);
//        load_tablePhieuNhapKho(list);
        int soluongNum = Integer.parseInt(SL);

        boolean found = false;
        for (int i = 0; i < list.size(); i++) {
            PhieuNhapKho_1 Bill2 = list.get(i);
            if (Bill2.getManguyenlieu() == maNguyenlieu) {
                // Mã món đã tồn tại, cập nhật số lượng và kết thúc vòng lặp
                Bill2.setSoluong(Bill2.getSoluong() + soluongNum);
                found = true;
                break;

            }
        }
        if (!found) {
            // Mã món không tồn tại, thêm món mới vào danh sách
            PhieuNhapKho_1 Ver2 = new PhieuNhapKho_1(maNguyenlieu, Tennl, soluongNum, NgayNhap);
            list.add(Ver2);
            Object[] rowData = {maNguyenlieu, Tennl, soluongNum, NgayNhap};
            dtm2.addRow(rowData);
            jTable3.setModel(dtm2);
            load_tablePhieuNhapKho(list);
        } else {
            load_tablePhieuNhapKho(list);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
//        String tenmon = jTextField2.getText();
//        String soluong = txtSoLuongNhap.getText();
//
//        if (!tenmon.isEmpty() && !soluong.isEmpty()) {
//            try {
//
//                int maNguyenLieu = Integer.parseInt(tenmon);
//                int soLuongNhap = Integer.parseInt(soluong);
//
//                NhapKhoModel nhapkho = new NhapKhoModel();
//                nhapkho.setMaNguyenLieu(maNguyenLieu);
//                nhapkho.setSoLuongNhap(soLuongNhap);
//
//                boolean result = NhapkhoDAO.insertKho(nhapkho);
//                if (result) {
//                    JOptionPane.showMessageDialog(null, "Nhập kho thành công!");
//                    int currentId = GetId() + 1;
//                    load_tableMon(new NguyenlieuDAO().laydulieunguyenlieu());
//                } else {
//                    JOptionPane.showMessageDialog(null, "Nhập kho thất bại!");
//                }
//            } catch (NumberFormatException ex) {
//                JOptionPane.showMessageDialog(null, "Số lượng nhập không hợp lệ!");
//            }
//        } else {
//            JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin để thực hiện nhập kho!");
//        }
        for (PhieuNhapKho_1 item : list) {
            int maNguyenLieu = item.getManguyenlieu();
            String TenNguyenLieu=item.getTennguyenlieu();
            int soLuongNhap = item.getSoluong();

            // Create NhapKhoModel object for each item
            NhapKhoModel nhapkho = new NhapKhoModel();
            nhapkho.setMaNguyenLieu(maNguyenLieu);
            nhapkho.setSoLuongNhap(soLuongNhap);
            // Assuming you have a field for the date

            // Insert into the warehouse and check the result
            boolean result = NhapkhoDAO.insertKho(nhapkho);
            if (!result) {
                JOptionPane.showMessageDialog(null, "Nhập kho thất bại cho nguyên liệu: ");
                return;  // Exit the method if any insertion fails
            }
        }

        // If all insertions are successful
        JOptionPane.showMessageDialog(null, "Nhập kho thành công!");
        load_tableMon(new NguyenlieuDAO().laydulieunguyenlieu());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
        int row = jTable3.getSelectedRow();
        int column = jTable3.getSelectedColumn();

        if (row != -1) { // Kiểm tra xem có dòng nào được chọn hay không
            String value = jTable3.getValueAt(row, 0).toString();
            String value2 = jTable3.getValueAt(row, 1).toString();
            String value3 = jTable3.getValueAt(row, 2).toString();
            // Hiển thị thông tin lên Textfield
            jTextField1.setText(value);
            jTextField2.setText(value2);
            txtSoLuongNhap.setText(value3);
        }
    }//GEN-LAST:event_jTable3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          int row = jTable3.getSelectedRow();
        if (row != -1) {
            list.remove(row);
            load_tablePhieuNhapKho(list);
        } else {
            JOptionPane.showMessageDialog(this, "Chọn nguyên liệu để xóa!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhieuNhapKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhieuNhapKho.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhieuNhapKho.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhieuNhapKho.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhieuNhapKho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txtSoLuongNhap;
    // End of variables declaration//GEN-END:variables
}
