/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TrangChu;

import DSNhanVien.DSNhanVien;
import DatMon.*;
import MySQLDB.Shared;
import GUI.Login.*;
import NguyenLieu.*;
import FOOD.*;
import HoaDon.HoaDon;
import MySQLDB.AccountDao;
import javax.swing.JOptionPane;
/**
 *
 * @author MyPC
 */
public class TrangChu extends javax.swing.JFrame {

    /**
     * Creates new form TrangChu
     */
    public TrangChu() {
        initComponents();
         setLocationRelativeTo(null);
        String role= Shared.getRole();
        System.out.println("vai tro " +role);
                setSize(1000, 920);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuTrangChu = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuDatmon = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuTT = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuNguyenLieu = new javax.swing.JMenu();
        jMenuItemNhapKho = new javax.swing.JMenuItem();
        jMenuItemNguyenLieu = new javax.swing.JMenuItem();
        jMenuNhanVien = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/nhahang1.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-50, -40, 1520, 1050);

        jMenuBar1.setBackground(new java.awt.Color(153, 255, 153));
        jMenuBar1.setBorder(new javax.swing.border.MatteBorder(null));

        jMenuTrangChu.setBackground(new java.awt.Color(153, 255, 255));
        jMenuTrangChu.setText("Trang Chủ");

        jMenuItem2.setText("Đăng Xuất");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuTrangChu.add(jMenuItem2);

        jMenuBar1.add(jMenuTrangChu);

        jMenuDatmon.setText("Đặt Món");

        jMenuItem3.setText("Món Ăn");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuDatmon.add(jMenuItem3);

        jMenuItem4.setText("Đặt Món");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenuDatmon.add(jMenuItem4);

        jMenuBar1.add(jMenuDatmon);

        jMenuTT.setText("Lịch Sử Thanh Toán");

        jMenuItem1.setText("Hóa đơn");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuTT.add(jMenuItem1);

        jMenuBar1.add(jMenuTT);

        jMenuNguyenLieu.setText("Kho Nguyên Liệu");

        jMenuItemNhapKho.setText("Nhập Kho");
        jMenuItemNhapKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNhapKhoActionPerformed(evt);
            }
        });
        jMenuNguyenLieu.add(jMenuItemNhapKho);

        jMenuItemNguyenLieu.setText("Nguyên Liệu");
        jMenuItemNguyenLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNguyenLieuActionPerformed(evt);
            }
        });
        jMenuNguyenLieu.add(jMenuItemNguyenLieu);

        jMenuBar1.add(jMenuNguyenLieu);

        jMenuNhanVien.setText("Nhân Viên");

        jMenuItem5.setText("QL_Nhân Viên");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenuNhanVien.add(jMenuItem5);

        jMenuBar1.add(jMenuNhanVien);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        dispose();
        Main DangNhap = new Main();
        DangNhap.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItemNhapKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNhapKhoActionPerformed
       // TODO add your handling code here:
       dispose();
         NhapKho_GUI nhapkho= new NhapKho_GUI();
         nhapkho.setVisible(true);
    }//GEN-LAST:event_jMenuItemNhapKhoActionPerformed

    private void jMenuItemNguyenLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNguyenLieuActionPerformed
        // TODO add your handling code here:
               dispose();
         NguyenLieu_GUI NL= new NguyenLieu_GUI();
         NL.setVisible(true);
    }//GEN-LAST:event_jMenuItemNguyenLieuActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        dispose();
        Food F= new Food();
        F.setVisible(true);

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
                dispose();
        DatMon Dm= new DatMon();
        Dm.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
          String username = Shared.getUser();
        String password = Shared.getPassword();
        int role = AccountDao.getUserRole(username, password);
        if (role != 0) {
            // Disable buttons or show a message indicating no permission

             JOptionPane.showMessageDialog(null, "Bạn không có quyền thao tác này !!!", "Thông báo", JOptionPane.YES_OPTION);
            dispose();
            TrangChu trangchu = new TrangChu();
            trangchu.setVisible(true);
        }
        else
        {
            DSNhanVien nv= new DSNhanVien();
            nv.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
                        dispose();
        HoaDon HD= new HoaDon();
        HD.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChu().setVisible(true);  
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDatmon;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItemNguyenLieu;
    private javax.swing.JMenuItem jMenuItemNhapKho;
    private javax.swing.JMenu jMenuNguyenLieu;
    private javax.swing.JMenu jMenuNhanVien;
    private javax.swing.JMenu jMenuTT;
    private javax.swing.JMenu jMenuTrangChu;
    // End of variables declaration//GEN-END:variables
}
